###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: memcached

#    redis:
#      image: redis:alpine
#      container_name: lemp73-redis

    mariadb:
      image: mariadb:10.4
      container_name: mariadb
      volumes:
        - ./db:/var/lib/mysql/
      environment:
        - MYSQL_ROOT_PASSWORD=rootdocker
        - MYSQL_DATABASE=lemp
        - MYSQL_USER=lemp
        - MYSQL_PASSWORD=lemp
      ports:
        - "3306:3306"

 #   postgres:
 #     image: postgres:11.1-alpine
 #     container_name: lemp73-postgres
 #     working_dir: /application
 #     volumes:
 #       - .:/application
 #     environment:
 #       - POSTGRES_USER=lemp
 #       - POSTGRES_PASSWORD=lemp
 #       - POSTGRES_DB=lemp
 #     ports:
 #       - "9004:5432"

    webserver:
      image: nginx:alpine
      container_name: nginx
      working_dir: /application
      volumes:
          - ./www:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./logs:/var/log/nginx
      ports:
       - "80:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: php-73
      working_dir: /application
      volumes:
        - ./www:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
        - ./logs/:/var/log/

    pma:
     image: phpmyadmin/phpmyadmin
     container_name: myadmin
     restart: always
     environment:
         PMA_HOST : mariadb
     ports:
       - "8000:80"

